version: '3.9'
services:
  app:
    container_name: 'omni.hidevs.ir'
    image: 'omni_hidevs_ir'
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - default

networks:
  default:
    external: true
    name: hidevs