version: '3.9'
services:
  app:
    container_name: 'omni-front'
    image: "omni-front"
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - default

networks:
  default:
    external: true
    name: hidevs